# Conclusion

## Lessons Learned
After completing this final project, we believe that we gained a better understanding of all the concepts that we have learned in this semster. Starting from researching online, we found this NVC Job Postings dataset and exported a `.csv` file for the use of our project. Then, leveraging the data processing skills we have learned, we cleaned up our data through properly dealing with NAs, removing duplicated elements that we did not need, and extracing more information such as locations by taking advantage of Google API. For the main part of project, we used many types of graphs we learnt in this semester, such as bar chart, box plot, histogram, ridgeline plot, and Cleveland dot plot. We also took advantage of the knowledge learnt from the Community Contribution assignment and drew several Word Cloud graphs to showcase our skills in dealing with text data. Last but not least, for the interactive component, we utizilied the Shiny app and created an interactive graph, from which users can check job salaries of the categories, agencies, or full/part time they select. Overall, we have learnt a lot through EDAV in this semester, and we really enjoy the process.

## Summary of Studies the Dataset
Here is a breif summary of some findings we got for the dataset.

When compared full-time jobs with part-time jobs, overall, the distributions of two types of job, are not have a huge differences, but the amount of part-time jobs are greatly less than full-time jobs. Most of jobs with the salary lower than 150k/yr and the range of these jobs' salaries are less than 50k. When the salary range over 50k, there is an obvious positive relationship between these two.

Planning Maintenance and Producement Building Operations have a extremly high annual salary mean. Human Resource Finance and Health Policy are also obviously distinguished with others since their annual are over 100k. Most job categories with the salary between 60k to 80k dollars per year, the categories in this range are mostly related with technology, innovation, finance, and service. The most popular positions are all in this range, and the top 30 categories has the annual salary range between 100k to 200k dollars per year. For the salary group less than 60k, they also have low annual salary range, their sizes of needness online are also small.