--- 
title: "EDAV Final Project Group 23"
author: "Shaofeng Wu, Chengyou Ju, Mingrui Liu, Yujing Song"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
This project is created by Shaofeng Wu (sw3428), Chengyou Ju (cj2624), Mingrui Liu (ml4404), Yujing Song (ys3251) for STAT GR5702 Final Project Group 23.

New York, a charming place which is attracting people all around city, has thousands of opportunities for people who have a dream to work in the city. In this way, New York government is posting different jobs every day so that the posted jobs can meet different requirements of different groups of people. Under this circumstance, it's interesting to analyze the trends of the job postings in the NYC. For instance, analyzing the areas and required skills of job postings can help people recognize the right places to find the right jobs. Finding the trends of salaries vs. job categories also provides people a fabulous tool to have a sense on which jobs are highly paid jobs so that they can try their best to learn more required skills and earn more money.

As graduate students who are actively seeking jobs and internships, we come up with the idea that we can choose a topic related to the current employment condition in New York. After doing some research, we decide to focus on studying the recent job postings in New York. We want to see, for instance, salary ranges for different categories of jobs, what skills are preferred by a particular kind of jobs, or if there is a relationship between job locations and salaries.
